TRAILING_STOP_LOSS_DEFAULT_PERCENT = (
    2.50  # Best Spot Loss value intra-day, based on experience
)
TRAILING_STOP_LOSS_PRICE_DECREASE_THRESHOLD = 0.00025
NUMBER_OF_DIGITS_IN_PRICE_BY_SYMBOL = {
    "XRP/EUR": 4,
}
