version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8000"
    env_file:
      - ./.env.docker-compose
    networks:
      - appNetwork
networks:
  appNetwork:
    driver: bridge
volumes:
  postgres:
    driver: local