DEFAULT_JOB_INTERVAL_SECONDS = 5  # 5 seconds
DEFAULT_TRAILING_STOP_LOSS_PERCENT = 5.0  # Best Spot Loss value intra-day, based on experience
TRAILING_STOP_LOSS_PRICE_DECREASE_THRESHOLD = 0.00025
NUMBER_OF_DECIMALS_IN_PRICE_BY_SYMBOL = {"BTC/EUR": 1, "XRP/EUR": 4}
DEFAULT_NUMBER_OF_DECIMALS_IN_PRICE = 2
NUMBER_OF_DECIMALS_IN_QUANTITY_BY_SYMBOL = {"BTC/EUR": 8, "ETH/EUR": 8, "XRP/EUR": 6}
DEFAULT_NUMBER_OF_DECIMALS_IN_QUANTITY = 4
AUTHORIZED_GOOGLE_USER_EMAILS = ["josemaria.sola.duran@gmail.com", "jmsola3092@gmail.com"]
DEFAULT_IN_MEMORY_CACHE_TTL_IN_SECONDS = 86_400  # 1 day
BUY_SELL_MINUTES_PAST_HOUR_EXECUTION_CRON_PATTERN = [0, 1, 2, 3, 5, 10, 15, 30, 31, 32, 33, 35, 45]
BUY_SELL_RELIABLE_TIMEFRAMES = ["4h", "1h"]
ANTICIPATION_ZONE_TIMEFRAMES = ["30m"]
# Event Emitter - Event names
SIGNALS_EVALUATION_RESULT_EVENT_NAME = "signals_evaluation_result"
TRIGGER_BUY_ACTION_EVENT_NAME = "trigger_buy_action"
# Bit2Me Fees
BIT2ME_MAKER_FEES = 0.00159
BIT2ME_TAKER_FEES = 0.00259
BIT2ME_MAKER_AND_TAKER_FEES_SUM = BIT2ME_MAKER_FEES + BIT2ME_TAKER_FEES
# Auto-Entry Trader
AUTO_ENTRY_TRADER_MINIMAL_AMOUNT_TO_INVEST = 25.0
