from crypto_trailing_stop.infrastructure.adapters.dtos.bit2me_market_config_dto import Bit2MeMarketConfigDto

DEFAULT_TRADING_MARKET_CONFIG = Bit2MeMarketConfigDto.model_construct(price_precision=4, amount_precision=6)
