name: crypto-stop-loss-ci (main)
on:
  push:
    branches:
      - main
      # - "hotfix/*"
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-tests-and-build-and-push:
    uses: ./.github/workflows/common.yml
    with:
      should_push: true