name: crypto-stop-loss-ci
on:
  push:
    branches:
      - main
      - 'release/**'  # Matches any branch under releases/
      - 'feature/**'  # Matches any branch under feature/
      - 'hotfix/**'  # Matches any branch under hotfix/
  workflow_dispatch: # Allows manual trigger from GitHub UI
jobs:
  test:
    name: Run tests with uv in Bullseye
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        run: |
          apt update && apt install -y curl
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies
        working-directory: backend
        run: uv sync --frozen
      - name: Run tests
        working-directory: backend
        run: |
          uv run pytest --cov=crypto_stop_loss --cov-report=xml --cov-report=html
  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Waits for test job to complete successfully
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set timestamp tag
        id: vars
        run: echo "TAG=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crypto-stop-loss-bot:${{ env.TAG }}
