name: crypto-stop-loss-ci
on:
  push:
    branches:
      - main
      # - "hotfix/*"
  workflow_dispatch: # Allows manual trigger from GitHub UI
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        run: |
          apt update && apt install -y curl
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies
        working-directory: backend
        run: uv sync --frozen
      - name: Run tests
        working-directory: backend
        run: |
          uv run task test
  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: tests  # Waits for test job to complete successfully
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from pyproject.toml
        id: extract_version
        working-directory: backend
        run: |
          APP_VERSION=$(grep '^version =' pyproject.toml | sed -E "s/version = \"(.*)\"/\1/")
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crypto-stop-loss-bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crypto-stop-loss-bot:${{ env.APP_VERSION }}
