name: crypto-stop-loss-ci (main)
on:
  push:
    branches:
      - main
      # - "hotfix/*"
  workflow_dispatch: # Allows manual trigger from GitHub UI
jobs:
  tests:
    uses: ./.github/workflows/common.yml  # Reuses the common CI workflow for running tests
  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: tests  # Waits for test job to complete successfully
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from pyproject.toml
        id: extract_version
        working-directory: backend
        run: |
          APP_VERSION=$(grep '^version =' pyproject.toml | sed -E "s/version = \"(.*)\"/\1/")
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crypto-stop-loss-bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crypto-stop-loss-bot:${{ env.APP_VERSION }}
