name: crypto-stop-loss-ci (non-main)
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
jobs:
  run-tests-and-build-no-push:
    uses: ./.github/workflows/common.yml
    with:
      should_push: false